title: "SY Tech & Dev Blog"
description: "Seungyeon Tech & Dev Blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: sylee199877@gmail.com
github_username: dltmddus1998
twitter_username:
instagram_username:
linkedin_username:
facebook_username:

# External API
giscus_repo: "dltmddus1998/dltmddus1998.github.io"
giscus_repoId: "R_kgDOJ6fqWg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOJ6fqWs4Cc7p7"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "2024-07-31"

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
